apiVersion: v1
kind: Secret
metadata:
  name: registration-api-secret
  namespace: apis
type: Opaque
stringData:
  DATABASE_URL: "postgresql://deviceuser:password@postgres.bank-db.svc.cluster.local:5432/devicedb"