apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-statistics-to-registration
  namespace: apis
spec:
  podSelector:
    matchLabels:
      app: registration-api
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: statistics-api
      ports:
        - protocol: TCP
          port: 8080
