apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: statistics-mtls
  namespace: apis
  annotations:
    kubernetes.io/ingress.class: nginx

    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "bank-apps/statistics-client-ca"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
spec:
  tls:
    - hosts:
        - bank.local
      secretName: statistics-server-tls
  rules:
    - host: bank.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: statistics-api
                port:
                  number: 80
